import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TransactionProvider } from "@/context/transactionContext";
import Navbar from "@/components/layout/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TransactionProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-greyFragments-#FAFAFA text-greyFragments-#333333 flex flex-col gap-3`}
      >
        <Navbar />
        {children}
      </body>
      </TransactionProvider>
    </html>
  );
}
